/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-06-25 08:30:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>AJAX Index</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t// 闭包写法\r\n");
      out.write("\t// onload 事件完毕\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t/* $(\"#btnCheckedRegisterName\").on(\"click\", function(){\r\n");
      out.write("\t\t\talert(\"++\");\r\n");
      out.write("\t\t});\t */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 点击事件\r\n");
      out.write("\t\t$(\"#btnCheckedRegisterName\").click(function(){\r\n");
      out.write("\t\t\t// 注册名\r\n");
      out.write("\t\t\t// ajax\r\n");
      out.write("\t\t\t// 响应\r\n");
      out.write("\t\t\tvar _registerName = $(\"#txtRegisterName\").val();\r\n");
      out.write("\t\t\t// alert(_registerName);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\t\tjquey \r\n");
      out.write("\t\t\t\t1 ajax() [最全的一个]\r\n");
      out.write("\t\t\t\t2 $.get()\r\n");
      out.write("\t\t\t\t3 $.post()\r\n");
      out.write("\t\t\t\t4 $.load()\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"imgLoading\").style.display = \"block\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// jquery ajax post \r\n");
      out.write("\t\t\t$.post(\r\n");
      out.write("\t\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/chekedRegisterName.action\",\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\"RegisterName\" : _registerName\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tfunction(data, status) {\r\n");
      out.write("\t\t\t\t\t\t//alert(data);\r\n");
      out.write("\t\t\t\t\t\t//alert(status)\r\n");
      out.write("\t\t\t\t\t\tif(status == \"success\") {\r\n");
      out.write("\t\t\t\t\t\t\t/* if(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"该注册名：\" + _registerName + \"已经被注册过\");\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"注册名可用\");\r\n");
      out.write("\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//alert(data);\r\n");
      out.write("\t\t\t\t\t\t\t//alert(data.id + \"|\" + data.name + \"|\" + data.age);\r\n");
      out.write("\t\t\t\t\t\t\t//$(\"#divResult\").html(data.id + \"|\" + data.name + \"|\" + data.age);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar _content = \"\";\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i = 0; i < data.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar obj = data[i];\r\n");
      out.write("\t\t\t\t\t\t\t\t_content += obj.name + \"|\" + obj.id + \"|\" + obj.age\r\n");
      out.write("\t\t\t\t\t\t\t\t_content += \"<br>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#divResult\").html(_content);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"imgLoading\").style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction loadXMLDoc() {\r\n");
      out.write("\t\t// 创建XMLHttpRequest对象，由它发起和服务器的请求\r\n");
      out.write("\t\tvar xmlhttp;\r\n");
      out.write("\t\tif (window.XMLHttpRequest)\r\n");
      out.write("\t\t  {// code for IE7+, Firefox, Chrome, Opera, Safari\r\n");
      out.write("\t\t  xmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t  {// code for IE6, IE5\r\n");
      out.write("\t\t  xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* var _name = \"tom\";\r\n");
      out.write("\t\tvar _age = 99; */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar _name = document.getElementById(\"txtName\").value;\r\n");
      out.write("\t\tvar _age = document.getElementById(\"txtAge\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(_name == \"\" || _age == \"\") {\r\n");
      out.write("\t\t\talert(\"名字和年龄不能为空\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\txmlhttp.onreadystatechange = function() {\r\n");
      out.write("\t\t\tif(xmlhttp.readyState == 4) {\r\n");
      out.write("\t\t\t\tif(xmlhttp.status == 200) {\r\n");
      out.write("\t\t\t\t\t// 服务器响应值\r\n");
      out.write("\t\t\t\t\tvar responseValue = xmlhttp.responseText;\r\n");
      out.write("\t\t\t\t\t// 响应值放在div之间\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"myDiv\").innerHTML=responseValue;\r\n");
      out.write("\t\t\t\t} else if(xmlhttp.status == 404) {\r\n");
      out.write("\t\t\t\t\talert(\"未找到请求资源\");\r\n");
      out.write("\t\t\t\t} else if(xmlhttp.status == 500) {\r\n");
      out.write("\t\t\t\t\talert(\"服务器内部错误\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"操作失败，请联系服务器管理员\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// readyState = 4 是发送成功状态\r\n");
      out.write("\t\t\t// status = 200 这个是响应状态码\r\n");
      out.write("\t\t\t/* if (xmlhttp.readyState==4 && xmlhttp.status==200)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t// 服务器响应值\r\n");
      out.write("\t\t\t\t\tvar responseValue = xmlhttp.responseText;\r\n");
      out.write("\t\t\t\t\t// 响应值放在div之间\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"myDiv\").innerHTML=responseValue;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t} */\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t/* xmlhttp.open(\r\n");
      out.write("\t\t\t\t\"GET\",\r\n");
      out.write("\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/load.action?name=\" + _name, true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\txmlhttp.send(); */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\txmlhttp.open(\r\n");
      out.write("\t\t\t\t\"POST\",\r\n");
      out.write("\t\t\t\t\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/load.action\", true);\r\n");
      out.write("\t\txmlhttp.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\txmlhttp.send(\"name=\" + _name + \"&age=\" + _age);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"myDiv\"><h3>Let AJAX change this text</h3></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t 你的名字: <input type=\"text\" id=\"txtName\">;\r\n");
      out.write("\t\t <br>\r\n");
      out.write("\t\t你的年龄: <input type=\"text\" id=\"txtAge\">;\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<button type=\"button\" onclick=\"loadXMLDoc()\">Change Content</button>\r\n");
      out.write("\t\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<legend>注册表单</legend>\r\n");
      out.write("\t\t注册名 <input type=\"text\" id=\"txtRegisterName\"> \r\n");
      out.write("\t\t<button id=\"btnCheckedRegisterName\">检查注册名是否被注册</button> \r\n");
      out.write("\t\t<img \r\n");
      out.write("\t\t\tid=\"imgLoading\"\r\n");
      out.write("\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/image/loading.gif\" style=\"display: none;\">\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"divResult\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
